"""
Stage 5B-2: AI Advisory <-> Automation pipeline integration tests.

    CanonicalEvent (attendance.marked)
              |
    Event Bus (InMemoryEventBus, same transport contract as Redis --
              see app/events/bus.py)
              |
    EventBusRunner -> EventConsumer (Event Processor)
              |
        RuleEngine (existing, deterministic -- attendance % < 75)
              |
        WorkflowEngine._execute_steps()
              |          \\
              |           `-- ai_context.for_event() -> REAL Stage 5B-1
              |                app.analytics.advisory.get_ai_advisory()
              |                -> REAL Stage 5A trained model
              |
        ActionExecutor -> create_notification / send_email / send_sms
              |
        NotificationService (mock email/SMS providers -- external
              network is what's mocked here, never the AI/automation
              chain itself)

Model lifecycle mirrors tests/test_ai_advisory.py exactly: train once
into a throwaway artifact path per test session and point risk.py's
cached loader at it, so predictions come from a real, freshly-trained
Stage 5A RandomForestClassifier -- nothing about the model itself is
mocked in the success-path tests. Only test_ai_failure_* deliberately
points at a missing artifact to exercise the real "model not trained"
failure path end-to-end.

Feature values for the HIGH/lower-risk cases below were chosen to sit
at (or very near) the centres of the synthetic HIGH/LOW training
clusters generated by app.analytics.training.generate_training_dataset
(see that module's _CLASS_PARAMS) -- they are not hand-picked to force
a particular output; they simply ask the real model about a clearly
at-risk vs. clearly not-at-risk student profile and check what it
actually says.
"""
from __future__ import annotations

import pytest

from app.analytics import model as model_module
from app.analytics import risk as risk_module
from app.analytics import training as training_module
from app.analytics.schemas import StudentRiskFeaturesInput
from app.automation import ai_context as ai_context_module
from app.automation.consumer import EventConsumer
from app.automation.events import CanonicalEvent, EventType
from app.automation.producer import make_attendance_marked_event, make_fee_paid_event
from app.automation.rules import RuleEngine
from app.automation.store import InMemoryExecutionStore
from app.automation.workflows import WorkflowEngine
from app.events.bus import InMemoryEventBus
from app.events.runner import EventBusRunner
from app.notifications.providers import MockSMSProvider, ProviderResult
from app.notifications.service import NotificationService

# ---------------------------------------------------------------------
# Real Stage 5A model fixture -- identical pattern to
# tests/test_ai_advisory.py's trained_model_path/use_real_model, so the
# automation-layer tests exercise the exact same real, trained
# estimator that Stage 5B-1's own unit tests do.
# ---------------------------------------------------------------------


@pytest.fixture(scope="module")
def trained_model_path(tmp_path_factory):
    scratch_dir = tmp_path_factory.mktemp("automation_ai_artifacts")
    scratch_path = scratch_dir / "risk_model.joblib"

    dataset = training_module.generate_training_dataset()
    estimator = training_module.train_model(dataset)
    model_module.save_model(estimator, path=scratch_path)

    return scratch_path


@pytest.fixture()
def use_real_model(trained_model_path, monkeypatch):
    """Point the real, trained Stage 5A model at a scratch artifact --
    this is the REAL model/estimator, loaded through the REAL
    app.analytics.risk.predict_risk / app.analytics.advisory.get_ai_advisory
    call path. Nothing about prediction itself is mocked."""
    monkeypatch.setattr(risk_module, "MODEL_PATH", trained_model_path)
    risk_module.reset_model_cache()
    yield
    risk_module.reset_model_cache()


@pytest.fixture()
def use_missing_model(tmp_path, monkeypatch):
    """Point at a path where no artifact has ever been trained/saved --
    a genuine (not mocked) ModelNotTrainedError failure path, exercised
    all the way through the automation chain."""
    monkeypatch.setattr(risk_module, "MODEL_PATH", tmp_path / "does_not_exist.joblib")
    risk_module.reset_model_cache()
    yield
    risk_module.reset_model_cache()


class RecordingEmailProvider:
    """Test double standing in for the real SMTP provider -- exactly the
    kind of "external SMTP/SMS" mocking Part 12 explicitly allows. Never
    touches the network; records what was actually sent so tests can
    assert on notification content without changing any production
    interface."""

    name = "recording_email"

    def __init__(self) -> None:
        self.sent: list[dict] = []

    def send(self, *, to: str, subject: str, body: str) -> ProviderResult:
        self.sent.append({"to": to, "subject": subject, "body": body})
        return ProviderResult(status="sent", provider=self.name, channel="email", provider_message_id="rec-1")


def make_consumer(notification_service: NotificationService | None = None):
    store = InMemoryExecutionStore()
    rule_engine = RuleEngine()
    workflow_engine = WorkflowEngine(store, notification_service=notification_service)
    return EventConsumer(rule_engine, workflow_engine, store), store


def attendance_event(**data_overrides) -> CanonicalEvent:
    """Build a real attendance.marked CanonicalEvent (the existing
    envelope, app/automation/events.py) with extra AI-relevant fields
    folded into `data` -- exactly the fields ai_context.py reads, using
    the same key names StudentRiskFeaturesInput already defines."""
    event = make_attendance_marked_event(
        attendance_percentage=data_overrides.pop("attendance_percentage", 65),
        aggregate_id=data_overrides.pop("aggregate_id", "ATT-AI-001"),
    )
    merged_data = dict(event.data)
    merged_data.update(data_overrides)
    return event.model_copy(update={"data": merged_data})


# =======================================================================
# TEST 1 -- High risk, full real chain, driven through the Event Bus
# =======================================================================


def test_high_risk_flows_event_to_notification_through_real_chain(use_real_model):
    """Event -> Event Bus -> Event Processor -> Rule Engine -> REAL AI
    Advisory Service (REAL Stage 5A model) -> Workflow Engine -> Action
    Executor -> Notification Service, proven through the real
    InMemoryEventBus + EventBusRunner transport, not just a direct
    consumer.consume() call."""
    recording_email = RecordingEmailProvider()
    notification_service = NotificationService(email_provider=recording_email, sms_provider=MockSMSProvider())

    store = InMemoryExecutionStore()
    consumer = EventConsumer(RuleEngine(), WorkflowEngine(store, notification_service=notification_service), store)
    bus = InMemoryEventBus()
    runner = EventBusRunner(bus, consumer)

    # Centre of the synthetic HIGH-risk training cluster (see module
    # docstring) -- attendance also < 75 so the existing deterministic
    # rule (RULE-001) fires and the workflow actually runs.
    event = attendance_event(
        aggregate_id="ATT-AI-HIGH",
        attendance_percentage=55,
        average_marks=42,
        missed_assignments=6,
        fee_overdue_indicator=True,
        contact_email="student@example.edu",
    )
    bus.publish(event)

    results = runner.run_once()

    assert len(results) == 1
    result = results[0]
    assert result.status == "workflow_triggered"
    assert result.workflow_run.workflow_id == "attendance_warning"
    assert result.workflow_run.status == "success"
    action_names = [a.action for a in result.workflow_run.action_results]
    assert action_names == ["create_notification", "send_email", "send_sms", "record_execution"]
    assert all(a.status == "success" for a in result.workflow_run.action_results)

    # The REAL model, not a hardcoded value, produced HIGH here.
    direct = risk_module.predict_risk(StudentRiskFeaturesInput(
        attendance_percentage=55, average_marks=42, missed_assignments=6, fee_overdue_indicator=True,
    ))
    assert direct.risk_level == "HIGH"

    # And that REAL result reached the notification the student/staff
    # actually received -- proving the AI result flowed all the way
    # downstream through the existing workflow/action context, not just
    # that the model predicted HIGH in isolation.
    assert len(recording_email.sent) == 1
    body = recording_email.sent[0]["body"]
    assert "Advisory only" in body
    assert "HIGH" in body
    assert "not an automatic decision" in body


def test_high_risk_result_is_advisory_only_not_a_decision(use_real_model):
    consumer, _ = make_consumer()
    event = attendance_event(
        aggregate_id="ATT-AI-HIGH-2",
        attendance_percentage=55,
        average_marks=42,
        missed_assignments=6,
        fee_overdue_indicator=True,
    )
    result = consumer.consume(event)
    assert result.status == "workflow_triggered"
    assert result.workflow_run.status == "success"
    # Nothing about this path ever approves/rejects/allocates/finalizes
    # anything -- the workflow's own action set (notify only) is the
    # architectural enforcement of that; this just re-asserts it stayed
    # the same unmodified action set.
    assert [a.action for a in result.workflow_run.action_results] == [
        "create_notification", "send_email", "send_sms", "record_execution",
    ]


# =======================================================================
# TEST 2 -- Lower risk, REAL model, no fabricated HIGH-risk behavior
# =======================================================================


def test_lower_risk_does_not_fabricate_high_risk_behavior(use_real_model):
    recording_email = RecordingEmailProvider()
    notification_service = NotificationService(email_provider=recording_email, sms_provider=MockSMSProvider())
    consumer, _ = make_consumer(notification_service)

    # Attendance still has to be < 75 for the existing deterministic
    # rule to fire at all -- but everything else here sits in the
    # synthetic LOW-risk cluster (strong marks, no missed assignments,
    # no fee overdue), so the real model's *overall* assessment should
    # come back clearly lower than the HIGH case above, and must never
    # be reported as HIGH.
    event = attendance_event(
        aggregate_id="ATT-AI-LOWER",
        attendance_percentage=70,
        average_marks=85,
        missed_assignments=0,
        fee_overdue_indicator=False,
    )
    result = consumer.consume(event)

    assert result.status == "workflow_triggered"
    assert result.workflow_run.status == "success"

    direct = risk_module.predict_risk(StudentRiskFeaturesInput(
        attendance_percentage=70, average_marks=85, missed_assignments=0, fee_overdue_indicator=False,
    ))
    assert direct.risk_level != "HIGH"

    high_direct = risk_module.predict_risk(StudentRiskFeaturesInput(
        attendance_percentage=55, average_marks=42, missed_assignments=6, fee_overdue_indicator=True,
    ))
    assert direct.risk_score < high_direct.risk_score

    body = recording_email.sent[0]["body"]
    assert "risk assessment: HIGH" not in body


# =======================================================================
# TEST 3 -- Declining attendance pattern surfaced in advisory + context
# =======================================================================


def test_declining_attendance_pattern_reaches_workflow_context(use_real_model):
    recording_email = RecordingEmailProvider()
    notification_service = NotificationService(email_provider=recording_email, sms_provider=MockSMSProvider())
    consumer, _ = make_consumer(notification_service)

    declining_history = [90.0, 86.0, 82.0, 78.0, 74.0]  # oldest-first, matches test_ai_advisory.py
    event = attendance_event(
        aggregate_id="ATT-AI-DECLINING",
        attendance_percentage=74,
        attendance_history=declining_history,
    )

    # Verify what the adapter actually builds, independent of the
    # notification body's wording -- this is the "available in the
    # workflow context" assertion Part 6/13 asks for.
    advisory_result = ai_context_module.for_event(event)
    assert advisory_result is not None
    assert advisory_result.attendance_pattern == "DECLINING"

    result = consumer.consume(event)
    assert result.status == "workflow_triggered"
    assert result.workflow_run.status == "success"
    assert "DECLINING" in recording_email.sent[0]["body"]


# =======================================================================
# TEST 4 -- AI failure: no fake result, deterministic workflow continues
# =======================================================================


def test_ai_failure_does_not_fabricate_a_result(use_missing_model):
    """No trained model artifact available -- the REAL failure path in
    app.analytics.model.load_model / app.analytics.advisory.get_ai_advisory,
    not a mock raising an exception."""
    recording_email = RecordingEmailProvider()
    notification_service = NotificationService(email_provider=recording_email, sms_provider=MockSMSProvider())
    consumer, _ = make_consumer(notification_service)

    event = attendance_event(aggregate_id="ATT-AI-FAIL", attendance_percentage=60)

    advisory_result = ai_context_module.for_event(event)
    assert advisory_result is not None
    assert advisory_result.ai_available is False
    assert advisory_result.risk_score is None
    assert advisory_result.risk_level is None

    result = consumer.consume(event)

    # Deterministic pipeline (rule -> workflow -> notify) is unaffected
    # by the AI being unavailable -- this project's explicit,
    # architecturally-documented choice (AI is advisory, never a
    # dependency of the deterministic path) per Part 10/Part 9.
    assert result.status == "workflow_triggered"
    assert result.workflow_run.status == "success"

    body = recording_email.sent[0]["body"]
    # Must say AI was unavailable, and must NOT claim any risk level --
    # i.e. never silently report a fabricated success.
    assert "unavailable" in body.lower()
    assert "risk assessment: HIGH" not in body
    assert "risk assessment: MEDIUM" not in body
    assert "risk assessment: LOW" not in body


def test_ai_failure_never_raises_out_of_the_workflow(use_missing_model):
    consumer, _ = make_consumer()
    event = attendance_event(aggregate_id="ATT-AI-FAIL-2", attendance_percentage=60)
    # Must not raise -- a missing model must degrade, not crash the chain.
    result = consumer.consume(event)
    assert result.status == "workflow_triggered"


def test_ai_unexpected_exception_is_contained_by_the_adapter(use_real_model, monkeypatch):
    """Belt-and-braces: even an unexpected exception from the AI
    Advisory Service itself (not just the documented ModelNotTrained
    path) must not escape ai_context.for_event() and take down the
    deterministic workflow."""

    def _explode(features, attendance_history=None):
        raise RuntimeError("simulated unexpected AI failure")

    monkeypatch.setattr(ai_context_module, "get_ai_advisory", _explode)

    event = attendance_event(aggregate_id="ATT-AI-FAIL-3", attendance_percentage=60)
    assert ai_context_module.for_event(event) is None  # contained, not raised

    consumer, _ = make_consumer()
    result = consumer.consume(event)
    assert result.status == "workflow_triggered"
    assert result.workflow_run.status == "success"


# =======================================================================
# TEST 5 -- Duplicate event: no duplicate AI processing/workflow/notify
# =======================================================================


def test_duplicate_event_id_does_not_duplicate_ai_or_workflow_execution(use_real_model, monkeypatch):
    calls = {"n": 0}
    real_for_event = ai_context_module.for_event

    def _counting_for_event(event):
        calls["n"] += 1
        return real_for_event(event)

    monkeypatch.setattr(ai_context_module, "for_event", _counting_for_event)
    # WorkflowEngine imported ai_context as a module and calls
    # ai_context.for_event(...), so patching the module attribute above
    # is picked up without touching workflows.py.

    recording_email = RecordingEmailProvider()
    notification_service = NotificationService(email_provider=recording_email, sms_provider=MockSMSProvider())
    consumer, store = make_consumer(notification_service)

    event = attendance_event(
        aggregate_id="ATT-AI-DUP",
        attendance_percentage=55,
        average_marks=42,
        missed_assignments=6,
        fee_overdue_indicator=True,
    )

    first = consumer.consume(event)
    second = consumer.consume(event)  # same event_id, sent twice

    assert first.status == "workflow_triggered"
    assert second.status == "skipped_duplicate"
    assert second.workflow_run is None

    # AI advisory (and therefore the model) was invoked exactly once --
    # the existing Stage 2 idempotency check short-circuits before the
    # rule/workflow/AI path is ever reached a second time.
    assert calls["n"] == 1
    # Exactly one notification, one email, one SMS -- no duplicates.
    assert len(recording_email.sent) == 1


def test_duplicate_event_id_via_event_bus_does_not_duplicate_notification(use_real_model):
    """Same guarantee, this time proven through the real Event Bus
    transport (a producer retry re-publishing the same event_id)."""
    recording_email = RecordingEmailProvider()
    notification_service = NotificationService(email_provider=recording_email, sms_provider=MockSMSProvider())
    store = InMemoryExecutionStore()
    consumer = EventConsumer(RuleEngine(), WorkflowEngine(store, notification_service=notification_service), store)
    bus = InMemoryEventBus()
    runner = EventBusRunner(bus, consumer)

    event = attendance_event(aggregate_id="ATT-AI-DUP-BUS", attendance_percentage=50)
    bus.publish(event)
    bus.publish(event)  # same event_id republished

    results = runner.run_once(count=10)

    assert len(results) == 2
    statuses = [r.status for r in results]
    assert statuses.count("workflow_triggered") == 1
    assert statuses.count("skipped_duplicate") == 1
    assert len(recording_email.sent) == 1


# =======================================================================
# TEST 6 -- Existing Stage 1-4 (non-AI) behavior is unaffected
# =======================================================================


def test_fee_paid_workflow_still_works_unaffected_by_ai_integration(use_real_model):
    """fee.paid never goes near the AI Advisory Service (see
    ai_context.for_event -- only ATTENDANCE_MARKED is in scope), and
    must keep working exactly as it did before Stage 5B-2."""
    recording_email = RecordingEmailProvider()
    notification_service = NotificationService(email_provider=recording_email, sms_provider=MockSMSProvider())
    consumer, _ = make_consumer(notification_service)

    event = make_fee_paid_event(amount=1200.0, aggregate_id="FEE-AI-001")
    assert ai_context_module.for_event(event) is None

    result = consumer.consume(event)

    assert result.status == "workflow_triggered"
    assert result.workflow_run.workflow_id == "fee_payment_confirmation"
    assert result.workflow_run.status == "success"
    action_names = [a.action for a in result.workflow_run.action_results]
    assert action_names == ["create_notification", "send_email", "record_execution"]

    # No AI advisory note leaked into an unrelated workflow's notification.
    body = recording_email.sent[0]["body"]
    assert "Advisory only" not in body
    assert "risk assessment" not in body


def test_high_attendance_still_does_not_match_rule_ai_never_invoked(use_real_model, monkeypatch):
    """Rule Engine remains the deterministic gate it always was -- the
    AI Advisory Service only ever runs downstream of an already-matched
    rule (Part 6), never as a second rule engine deciding whether to fire."""
    calls = {"n": 0}
    real_for_event = ai_context_module.for_event

    def _counting_for_event(event):
        calls["n"] += 1
        return real_for_event(event)

    monkeypatch.setattr(ai_context_module, "for_event", _counting_for_event)

    consumer, _ = make_consumer()
    event = attendance_event(aggregate_id="ATT-AI-NOMATCH", attendance_percentage=90)

    result = consumer.consume(event)

    assert result.status == "no_rule_matched"
    assert result.workflow_run is None
    assert calls["n"] == 0  # workflow (and therefore AI) never ran


# =======================================================================
# Adapter unit coverage -- event-type scoping, mapping, failure guard
# =======================================================================


def test_ai_context_returns_none_for_non_attendance_event_types():
    for event_type, aggregate_type in (
        (EventType.FEE_PAID, "fee"),
        (EventType.HOSTEL_ALLOCATED, "hostel"),
        (EventType.EXAM_REGISTERED, "exam"),
    ):
        event = CanonicalEvent(
            event_type=event_type,
            aggregate_type=aggregate_type,
            aggregate_id="X-1",
            student_id="STU-001",
            data={},
        )
        assert ai_context_module.for_event(event) is None


def test_ai_context_maps_event_fields_to_features_used_by_real_model(use_real_model):
    event = attendance_event(
        aggregate_id="ATT-AI-MAP",
        attendance_percentage=55,
        average_marks=42,
        missed_assignments=6,
        fee_overdue_indicator=True,
    )
    via_adapter = ai_context_module.for_event(event)
    direct = risk_module.predict_risk(StudentRiskFeaturesInput(
        attendance_percentage=55, average_marks=42, missed_assignments=6, fee_overdue_indicator=True,
    ))
    assert via_adapter.risk_score == direct.risk_score
    assert via_adapter.risk_level == direct.risk_level
    assert via_adapter.model_version == direct.model_version
