"""create admissions table

Revision ID: 1ee7281ca523
Revises: c9eadf5a289d
Create Date: 2026-08-23 08:27:27.501022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ee7281ca523'
down_revision: Union[str, Sequence[str], None] = 'c9eadf5a289d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('application_number', sa.String(length=32), nullable=False),
    sa.Column('student_id', sa.UUID(), nullable=True),
    sa.Column('applicant_name', sa.String(length=120), nullable=False),
    sa.Column('applicant_email', sa.String(length=255), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=False),
    sa.Column('course', sa.String(length=120), nullable=False),
    sa.Column('enrollment_year', sa.Integer(), nullable=False),
    sa.Column('application_date', sa.Date(), nullable=False),
    sa.Column('admission_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('APPLIED', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'CANCELLED', name='admission_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admissions_applicant_email'), 'admissions', ['applicant_email'], unique=False)
    op.create_index(op.f('ix_admissions_application_number'), 'admissions', ['application_number'], unique=True)
    op.create_index(op.f('ix_admissions_student_id'), 'admissions', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admissions_student_id'), table_name='admissions')
    op.drop_index(op.f('ix_admissions_application_number'), table_name='admissions')
    op.drop_index(op.f('ix_admissions_applicant_email'), table_name='admissions')
    op.drop_table('admissions')
    # ### end Alembic commands ###
    # Postgres ENUM types are not dropped automatically when the table
    # that used them is dropped — without this, a downgrade followed by
    # a re-upgrade fails with "type admission_status already exists".
    sa.Enum(name='admission_status').drop(op.get_bind(), checkfirst=True)
